module.exports.output = 'songsCastellanoScore.pdf'
module.exports.margin = 25
module.exports.fontSize = 12
module.exports.fontSizeSmall = 10
module.exports.tooLong = 20
module.exports.size = 'A4'
module.exports.path = 'C:\\US\\songs\\Castellano'
module.exports.format = 'ab.x - .t.x (.y.x).v.d.hb'
module.exports.options = 'sa.sl'
module.exports.job = 'printList'
module.exports.db = 'C:\\Users\\49172\\AppData\\Roaming\\ultrastardx\\Ultrastar.db'